name: Build Android APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'

    - name: Scaffold Clean Flutter App
      run: |
        flutter create --org com.rana.portrait --project-name rana_portrait_camera temp_app
        cp -r temp_app/android .
        cp -r temp_app/ios .
        rm -rf temp_app

    - name: Get Dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Rana-Portrait-Camera
        path: build/app/outputs/flutter-apk/app-debug.apk
